const $=id=>document.getElementById(id); const key='jofit-v1'; let data=JSON.parse(localStorage.getItem(key)||'null')||{stats:{push:5,hang:0,lsit:0},week:{},history:[],weights:[],levels:{push:0,pull:0,lsit:0}}; let session=null,timerInt;
const ex={push:{name:'Full Push-ups',emoji:'💪',sets:3,target:3,why:'Builds chest, shoulders, triceps and whole-body tension. You already own 3–5 reps; we build quality volume before harder variations.',video:'https://www.youtube.com/results?search_query=Hybrid+Calisthenics+pushups'},squat:{name:'Bodyweight Squats',emoji:'🌱',sets:3,target:12,why:'Builds quads and glutes while practising useful hip and ankle range.',video:'https://www.youtube.com/results?search_query=Hybrid+Calisthenics+squats'},row:{name:'Bodyweight / Incline Rows',emoji:'🧗',sets:3,target:8,why:'Builds the back and biceps you need for your future pull-up. Choose an angle that makes the last reps challenging but clean.',video:'https://www.youtube.com/results?search_query=Hybrid+Calisthenics+pullups'},bridge:{name:'Glute Bridges',emoji:'🌉',sets:3,target:12,why:'Trains glutes and hip extension without needing equipment.',video:'https://www.youtube.com/results?search_query=glute+bridge+proper+form'},hollow:{name:'Hollow Hold',emoji:'🥐',sets:3,target:20,time:true,why:'Teaches the trunk tension that shows up everywhere in calisthenics.',video:'https://www.youtube.com/results?search_query=hollow+body+hold+calisthenics+form'},lsit:{name:'L-sit Quest Practice',emoji:'✨',sets:3,target:8,time:true,why:'Your fun skill: core compression, hip flexors, straight-arm support and shoulder stability. Start tucked if needed.',video:'https://www.youtube.com/results?search_query=L+sit+progression+beginner'},hang:{name:'Dead Hang + Scapular Pull',emoji:'🐒',sets:3,target:15,time:true,why:'Builds grip and shoulder control and gets you comfortable hanging before pull-up work.',video:'https://www.youtube.com/results?search_query=Hybrid+Calisthenics+pullups'},lunge:{name:'Reverse Lunges',emoji:'⚔️',sets:3,target:8,each:true,why:'Single-leg strength and balance with an easy-to-scale bodyweight movement.',video:'https://www.youtube.com/results?search_query=reverse+lunge+proper+form'},deadbug:{name:'Dead Bug',emoji:'🐞',sets:3,target:8,each:true,why:'Core control without needing endless crunches: keep your torso steady while your limbs move.',video:'https://www.youtube.com/results?search_query=dead+bug+exercise+proper+form'},mobility:{name:'Mobility Finish',emoji:'🧘',sets:1,target:8,time:true,why:'A short mix of hamstrings, hip flexors, deep squat and shoulders. Consistency matters more than heroic stretching.',video:'https://www.youtube.com/results?search_query=Movement+by+David+10+minute+flexibility'}};
const plans={A:['push','squat','row','bridge','hollow','lsit','mobility'],B:['row','lunge','push','bridge','deadbug','hang','mobility'],Q:['push','squat','row','hollow']};
function save(){localStorage.setItem(key,JSON.stringify(data))} function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='skills')renderSkills();if(id==='journey')renderJourney()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
function weekId(){let d=new Date(),jan=new Date(d.getFullYear(),0,1);return d.getFullYear()+'-'+Math.ceil((((d-jan)/86400000)+jan.getDay()+1)/7)}
function init(){let w=weekId();data.week[w]??={};$('wkA').checked=!!data.week[w].A;$('wkB').checked=!!data.week[w].B;$('wkC').checked=!!data.week[w].C;$('pushMax').value=data.stats.push;$('hangMax').value=data.stats.hang;$('lsitMax').value=data.stats.lsit;let day=new Date().getDay(), names=['Sunday recovery','Monday: save your energy','Tuesday ⚔️ Push Quest','Wednesday recovery','Thursday 🐒 Pull Quest','Friday date day ❤️','Saturday adventure'];$('todayTitle').textContent=names[day];$('todaySub').textContent=day===2?'Push + legs + L-sit. About 45 minutes.':day===4?'Pull + legs + hanging. About 45 minutes.':'No compulsory workout today. Your programme fits your life.';$('streak').textContent='⚡ '+data.history.length+' quests';save()}
function saveWeek(){let w=weekId();data.week[w]={A:$('wkA').checked,B:$('wkB').checked,C:$('wkC').checked};save()} function saveStats(){data.stats={push:+$('pushMax').value,hang:+$('hangMax').value,lsit:+$('lsitMax').value};save()}
function adjusted(id){let e={...ex[id]};if(id==='push')e.target=Math.max(3,Math.min(8,Math.floor(data.stats.push*.7)));return e}
function startWorkout(type){session={type,i:0,results:[],quick:type==='Q'};show('workout');$('workTag').textContent=type==='A'?'TUESDAY · PUSH + L-SIT':type==='B'?'THURSDAY · PULL + LEGS':'15 MIN RESCUE QUEST';$('workTitle').textContent=type==='A'?'Push Quest ⚔️':type==='B'?'Pull Quest 🐒':'Tiny Quest 😭';renderExercise()}
function quickWorkout(){startWorkout('Q')}
function renderExercise(){clearInterval(timerInt);let ids=plans[session.type];if(session.i>=ids.length)return finishWorkout();let id=ids[session.i],e=adjusted(id);$('workProgress').textContent=(session.i+1)+' / '+ids.length;$('exerciseCard').innerHTML='<div class="card exercise"><div class="emoji">'+e.emoji+'</div><h2>'+e.name+'</h2><p><b>'+e.sets+' set'+(e.sets>1?'s':'')+' × '+e.target+(e.time?' sec':e.each?' each side':' reps')+'</b></p><div class="sets">'+Array.from({length:e.sets},(_,i)=>'<button class="set" onclick="this.classList.toggle(\'done\')">Set '+(i+1)+' ✓</button>').join('')+'</div><button onclick="rest(90)">⏱ Rest 90 sec</button><div class="timer" id="timer"></div><div class="why"><b>Why this?</b><br>'+e.why+'<br><a href="'+e.video+'" target="_blank">▶ Find the tutorial on YouTube</a></div><p><b>How did it feel?</b></p><div class="feel"><button onclick="feel(\'easy\')">😌 Easy</button><button onclick="feel(\'good\')">👍 Good</button><button onclick="feel(\'hard\')">🥵 Hard</button><button onclick="feel(\'fail\')">💀 Nope</button></div><button class="primary next" onclick="nextExercise()">Next exercise →</button></div>'}
function feel(v){session.feel=v;toast(v==='easy'?'Noted. We may level this up ✨':v==='fail'?'No shame. We scale it, not quit it.':'Logged 👍')}
function nextExercise(){let id=plans[session.type][session.i],e=adjusted(id);session.results.push({id,target:e.target,feel:session.feel||'good'});session.feel=null;session.i++;renderExercise()}
function rest(sec){clearInterval(timerInt);let t=sec,el=$('timer');el.textContent='1:30';timerInt=setInterval(()=>{t--;el.textContent=Math.floor(t/60)+':'+String(t%60).padStart(2,'0');if(t<=0){clearInterval(timerInt);el.textContent='GO ✨'}},1000)}
function finishWorkout(){let entry={date:new Date().toLocaleDateString(),type:session.type,results:session.results};data.history.unshift(entry);let w=weekId();data.week[w]??={};if(session.type==='A'||session.type==='B')data.week[w][session.type]=true;adapt(session.results);save();init();$('exerciseCard').innerHTML='<div class="card soft exercise"><div class="emoji">🎉</div><h2>QUEST COMPLETE</h2><p>You showed up. That is the part the whole programme depends on.</p><button class="primary" onclick="show(\'home\')">Back to quest board</button></div>';$('workProgress').textContent='COMPLETE'}
function adapt(results){results.forEach(r=>{if(r.id==='push'&&r.feel==='easy')data.stats.push=Math.max(data.stats.push,r.target+1);if(r.id==='hang'&&r.feel==='easy')data.stats.hang=Math.max(data.stats.hang,r.target+5);if(r.id==='lsit'&&r.feel==='easy')data.stats.lsit=Math.max(data.stats.lsit,r.target+2)})}
const trees={push:['3–5 full push-ups','3 × 5 clean','3 × 8 clean','10 consecutive 🏆','Slow tempo push-ups','Close-grip / decline','Archer progression 🔥'],pull:['Rows','Dead hang 30 sec','Scapular pulls','Assisted pull-ups','Controlled negatives','FIRST PULL-UP 🏆','3–5 pull-ups 🔥'],lsit:['Support hold','Tuck hold 5 sec','Tuck L-sit 10 sec','One-leg L-sit','FULL L-SIT 🏆']};
function renderSkills(){let lv={push:data.stats.push>=10?3:data.stats.push>=8?2:data.stats.push>=5?1:0,pull:data.stats.hang>=30?1:0,lsit:data.stats.lsit>=10?2:data.stats.lsit>=5?1:0};$('skillTrees').innerHTML=Object.entries(trees).map(([k,a])=>'<div class="tree"><h3>'+({push:'💪 Push Quest',pull:'🐒 Pull Quest',lsit:'✨ L-sit Quest'}[k])+'</h3>'+a.map((n,i)=>'<div class="node '+(i<lv[k]?'done':i===lv[k]?'current':'locked')+'">'+(i<lv[k]?'✓ ':i===lv[k]?'→ ':'🔒 ')+n+'</div>').join('<div class="arrow">↓</div>')+'</div>').join('')}
function renderJourney(){$('records').innerHTML='<p>💪 Push-up max: <b>'+data.stats.push+'</b></p><p>🐒 Dead hang: <b>'+data.stats.hang+' sec</b></p><p>✨ Tuck L-sit: <b>'+data.stats.lsit+' sec</b></p>';$('history').innerHTML=data.history.length?data.history.map(h=>'<div class="historyItem"><b>'+h.date+'</b> · '+(h.type==='A'?'Push Quest':h.type==='B'?'Pull Quest':'Tiny Quest')+' ✓</div>').join(''):'<p class="muted">Your first completed workout will appear here.</p>';$('weights').innerHTML=data.weights.map(w=>'<small>'+w.date+' · '+w.value+' kg</small><br>').join('')}
function saveWeight(){let v=+$('weight').value;if(v){data.weights.unshift({date:new Date().toLocaleDateString(),value:v});save();renderJourney();$('weight').value=''}}
function toast(s){let t=$('toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',1800)} init();